# Generated by Django 5.1.1 on 2024-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu_mark', models.IntegerField()),
                ('tdp', models.FloatField()),
                ('socket', models.CharField(max_length=50)),
                ('cores', models.IntegerField()),
            ],
        ),
    ]
