# Generated by Django 5.1.1 on 2024-10-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='burst_clock_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='turbo_clock_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
