# Generated by Django 5.1.1 on 2024-10-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0002_cpu_burst_clock_time_cpu_turbo_clock_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='burst_clock_time',
        ),
        migrations.AddField(
            model_name='cpu',
            name='base_clock_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='turbo_clock_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
