# Generated by Django 5.1.1 on 2024-10-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0003_remove_cpu_burst_clock_time_cpu_base_clock_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='base_clock_time',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='turbo_clock_time',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='socket',
            field=models.CharField(max_length=100),
        ),
    ]
