# Generated by Django 5.1.1 on 2024-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0004_remove_cpu_base_clock_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('G3mark', models.IntegerField()),
                ('G2mark', models.IntegerField()),
                ('tdp', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.FloatField(default=170),
            preserve_default=False,
        ),
    ]
