# Generated by Django 5.1.1 on 2024-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0005_gpu_cpu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
