# Generated by Django 5.1.1 on 2024-10-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0006_alter_gpu_tdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
