# Generated by Django 5.1.1 on 2024-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0007_alter_cpu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.FloatField(blank=200, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tdp',
            field=models.FloatField(blank=170, null=True),
        ),
    ]
