# Generated by Django 5.1.1 on 2024-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0008_alter_cpu_price_alter_gpu_tdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('tdp_support', models.IntegerField()),
                ('fan_size', models.IntegerField()),
                ('noise_level', models.FloatField()),
                ('socket_compatibility', models.CharField(max_length=100)),
                ('rpm_range', models.CharField(max_length=50)),
                ('number_of_fans', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='tdp',
            new_name='Tdp',
        ),
    ]
