# Generated by Django 5.1.1 on 2024-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0010_case_monitor_motherboard_operatingsystem_powersupply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='noise_level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cpucooler',
            name='tdp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
