# Generated by Django 5.1.1 on 2024-10-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0011_alter_case_price_alter_cpucooler_noise_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cpucooler',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='operatingsystem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='price',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='price',
        ),
    ]
