# Generated by Django 5.1.1 on 2024-10-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0012_remove_case_price_remove_cpu_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='price_per_gb',
        ),
    ]
