# Generated by Django 5.1.1 on 2024-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0013_remove_storage_price_per_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='price_per_gb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
