# Generated by Django 5.1.1 on 2024-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0014_alter_ram_price_per_gb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powersupply',
            name='wattage',
            field=models.CharField(max_length=100),
        ),
    ]
