# Generated by Django 5.1.1 on 2024-10-07 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0015_alter_powersupply_wattage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_motherboard', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_ram', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_storage', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_psu', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_case', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_os', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_monitor', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
