# Generated by Django 5.1.1 on 2024-10-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0016_pcselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcselection',
            name='selected_case',
        ),
        migrations.RemoveField(
            model_name='pcselection',
            name='selected_monitor',
        ),
        migrations.RemoveField(
            model_name='pcselection',
            name='selected_os',
        ),
        migrations.RemoveField(
            model_name='pcselection',
            name='selected_psu',
        ),
        migrations.RemoveField(
            model_name='pcselection',
            name='selected_storage',
        ),
        migrations.RemoveField(
            model_name='pcselection',
            name='total_price',
        ),
    ]
