# Generated by Django 5.1.1 on 2024-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0017_remove_pcselection_selected_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcselection',
            name='selected_case',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='selected_cpu_cooler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='selected_monitor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='selected_os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='selected_psu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='selected_storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pcselection',
            name='session_id',
            field=models.CharField(default=10, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
