# Generated by Django 5.1.1 on 2024-10-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0018_pcselection_selected_case_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('selected_cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_motherboard', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_ram', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_case', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_psu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_os', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_cpu_cooler', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PCSelection',
        ),
    ]
