# Generated by Django 5.1.1 on 2024-10-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0019_pcbuild_delete_pcselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='selected_monitor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
