# Generated by Django 5.1.1 on 2024-10-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0020_pcbuild_selected_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu',
            old_name='Name',
            new_name='name',
        ),
    ]
