# Generated by Django 5.1.1 on 2025-04-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0023_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(default='My Build', max_length=100)),
                ('selected_cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_motherboard', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_ram', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_case', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_psu', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_os', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_cpu_cooler', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_monitor', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcpicker.customuser', to_field='user_id')),
            ],
        ),
    ]
