# Generated by Django 5.1.1 on 2025-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0024_savebuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savebuild',
            name='user',
        ),
        migrations.AddField(
            model_name='savebuild',
            name='user_id',
            field=models.CharField(default=121, max_length=100),
        ),
    ]
