# Generated by Django 5.1.1 on 2025-07-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0025_remove_savebuild_user_savebuild_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpu_mark', models.IntegerField(default=0)),
                ('tdp', models.FloatField(default=0.0)),
                ('socket', models.CharField(max_length=100)),
                ('cores', models.IntegerField(default=0)),
            ],
        ),
    ]
