# Generated by Django 5.1.1 on 2025-07-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0026_live_cpu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_cpu',
            name='cpu_mark',
        ),
    ]
