# Generated by Django 5.1.1 on 2025-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0027_remove_live_cpu_cpu_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_cpu',
            name='cores',
            field=models.CharField(max_length=100),
        ),
    ]
