# Generated by Django 5.1.1 on 2025-07-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0028_alter_live_cpu_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_cpu',
            name='cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='live_cpu',
            name='tdp',
            field=models.IntegerField(default=0),
        ),
    ]
