# Generated by Django 5.1.1 on 2025-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcpicker', '0029_alter_live_cpu_cores_alter_live_cpu_tdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_cpu',
            name='cpu_mark',
            field=models.CharField(default='NotUpdated', max_length=100),
            preserve_default=False,
        ),
    ]
